DROP TABLE recipes IF EXISTS;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
first VARCHAR NOT NULL,
last VARCHAR NOT NULL,
email VARCHAR UNIQUE NOT NULL,
password VARCHAR NOT NULL,
userpic VARCHAR,
usertimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipes (
id SERIAL PRIMARY KEY,
creator INTEGER NOT NULL REFERENCES users(id),
title VARCHAR UNIQUE NOT NULL,
category VARCHAR NOT NULL,
ingredients VARCHAR [] NOT NULL,
directions VARCHAR [] NOT NULL ,
picture VARCHAR,
servings INTEGER,
vegan BOOLEAN DEFAULT false,
duration INTEGER,
favorite BOOLEAN DEFAULT false,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE menu (
id SERIAL PRIMARY KEY,
creator INTEGER NOT NULL REFERENCES users(id),
recipe_id INTEGER NOT NULL,
menutimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);